### ISSUE TITLE
Found a small bug with strings

### ISSUE THREAD

**Issue by hyphenrf** [polytypic/f-omega-mu#1]
not sure what causes it, but I thought I'd report it here first before investigating further.
smallest example:
```ocaml
"hello"
```
just typing that, I get an interpreter and js output both saying:
```js
"use strict"
```
![image](https://user-images.githubusercontent.com/26802762/194975488-28fd0fb3-63e6-49e9-afdd-7f08fe8b2b75.png)

**Comment by polytypic** [comment]
Hmm... That seems to be due to Terser.  Uncheck Terser and you get the expected output.  Perhaps the Terser configuration needs adjustment.

**Comment by hyphenrf** [comment]
yep looks like it's the culprit

**Comment by polytypic** [comment]
I submitted [an issue to Terser](https://github.com/terser/terser/issues/1273).  The behaviour seems like a bug to me, but let's see what the response is.

**Comment by polytypic** [comment]
Interestingly this seems to be related the ["Directive Prologue"](https://tc39.es/ecma262/multipage/ecmascript-language-source-code.html#sec-directive-prologues-and-the-use-strict-directive) feature of ECMAScript.  So, I guess this has to be worked around in some way or another in the code generator.

**Comment by polytypic** [comment]
Thanks for reporting the bug!

**Comment by hyphenrf** [comment]
No worries. Thanks for the playground
It's quite educational for someone like me to have a working SystemF running interactively
